// Code generated by "stringer -type=ColumnReferenceType"; DO NOT EDIT

package masq

import "fmt"

const _ColumnReferenceType_name = "ColumnRegularColumnForeignKeyRegisterColumnForeignKeyReference"

var _ColumnReferenceType_index = [...]uint8{0, 13, 37, 62}

func (i ColumnReferenceType) String() string {
	if i < 0 || i >= ColumnReferenceType(len(_ColumnReferenceType_index)-1) {
		return fmt.Sprintf("ColumnReferenceType(%d)", i)
	}
	return _ColumnReferenceType_name[_ColumnReferenceType_index[i]:_ColumnReferenceType_index[i+1]]
}
